# Generated by auth_service (Wed, 22 Feb 2017 12:36:43 GMT).

LIBS   = -pkgs conduit.mirage,functoria.runtime,magic-mime,mirage-clock-unix,mirage-console.unix,mirage-fs-unix,mirage-http,mirage-logs,mirage-types.lwt,mirage-unix,mirage.runtime,nocrypto.lwt,re.str,tcpip.stack-socket,tcpip.tcpv4-socket,tcpip.udpv4-socket
PKGS   = functoria lwt magic-mime mirage-clock-unix mirage-conduit mirage-console mirage-fs-unix mirage-http mirage-logs mirage-types mirage-types-lwt mirage-unix nocrypto re tcpip
SYNTAX = -tags "warn(A-4-41-44),debug,bin_annot,strict_sequence,principal,safe_string"

FLAGS  = -cflag -g -lflags -g,-linkpkg

SYNTAX += -tag-line "<static*.*>: warn(-32-34)"

BUILD  = ocamlbuild -use-ocamlfind $(LIBS) $(SYNTAX) $(FLAGS)
OPAM   = opam

export PKG_CONFIG_PATH=$(shell opam config var prefix)/lib/pkgconfig

export OPAMVERBOSE=1
export OPAMYES=1

.PHONY: all depend clean build main.native
all:: build

depend::
	$(OPAM) install $(PKGS) --verbose

main.native:
	$(BUILD) main.native

main.native.o:
	$(BUILD) main.native.o

build: main.native
	ln -nfs _build/main.native mir-auth_service

clean::
	ocamlbuild -clean

-include Makefile.user
